name: "Thomas' Coding-Tagebuch"
description: '{Über: [JavaScript&hearts;, Coding, etc.]}'
meta_description: "Thomas Rehm blogt."

markdown: kramdown
highlighter: pygments
logo: 'assets/images/profile.jpg'
paginate: 15
baseurl: /
domain_name: 'https://thomasrehm.github.io'
google_analytics: 'UA-29328100-2'

# Details for the RSS feed generator
#url:            'blog url'
author:         'Thomas Rehm'

gems: [jekyll-paginate]